Endpoints:
  - Name: "Bedrock - NovaPro"
    Host: "http://54.255.252.95:8069/api/v1"
    Model: "us.amazon.nova-pro-v1:0"
    ApiKey: BEDROCK_PROXY_API_KEY
  - Name: "DashScope"
    Host: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1"
    Model: "qwen-plus"
    ApiKey: DASHSCOPE_API_KEY
  - Name: "OpenAI"
    Host: "https://api.openai.com/v1"
    Model: "gpt-4-turbo"
    ApiKey: OPENAI_API_KEY
  - Name: "Anthropic"
    Host: "https://api.anthropic.com/v1"
    Model: "claude-3-7-sonnet"
    ApiKey: ANTHROPIC_API_KEY
  - Name: "LocalServer"
    Host: "http://localhost:8000/v1"
    Model: "local-model"
    ApiKey: "dev-key"